services:
  - type: web
    name: citibike-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/frontend_v2.py --server.port $PORT --server.address 0.0.0.0
    plan: free